spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.jooq.JooqAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthContributorAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.jdbc.DataSourcePoolMetricsAutoConfiguration
      - org.apache.camel.component.quartz.springboot.QuartzComponentAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  config:
    activate:
      on-profile: development
    import: optional:consul:${CONSUL_URL:http://consul:8500}
  cloud:
    consul:
      config:
        m2m:
          enabled: false
        acl-token: ${CONSUL_ADMIN_TOKEN}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: ${ROOT_LOG_LEVEL:WARN}
    org.qubership.integration.platform.engine: DEBUG

qip:
  local-truststore:
    store:
      path: /app/truststore/defaulttruststore.jks
    certs:
      location: /app/cert/defaultsslcertificate
  internal-services:
    runtime-catalog:
      url: "http://runtime-catalog:8080"
